=== Vishvin95/Temporal-Event-Data-Platform/src/main/resources/Insert.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="inputData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="table" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="row">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="column" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="key" type="xs:string" />
													<xs:element name="value">
														<xs:simpleType>
															<xs:union
																memberTypes="xs:boolean xs:string xs:integer xs:double xs:decimal xs:date" />
														</xs:simpleType>
													</xs:element>
													<!-- validFrom and validTo is applicable to temporal events -->
													<xs:element name="validFrom" type="xs:dateTime" minOccurs="0"/>
													<xs:element name="validTo" type="xs:dateTime" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Vishvin95/Temporal-Event-Data-Platform/Insert.xml
<?xml version="1.0" encoding="UTF-8"?>
<inputData
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="src/main/resources/Insert.xsd">

	<table name="supervisor">
		<row>
			<column>
				<key>supId</key>
				<value>S1</value>
				<validFrom>2020-05-01T09:00:00</validFrom>
			</column>
			<column>
				<key>salary</key>
				<value>10000</value>
				<validFrom>2020-05-01T23:00:00</validFrom>
			</column>
			<column>
				<key>age</key>
				<value>31</value>
				<validFrom>2020-05-01T09:00:00</validFrom>
				<validTo>2020-05-11T03:00:00</validTo>
			</column>
			<column>
				<key>name</key>
				<value>Aman</value>
			</column>
		</row>
	</table>
</inputData>
