=== Vishvin95/Temporal-Event-Data-Platform/src/main/resources/SensorData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="sensorData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="domain">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="reading" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="key" type="xs:string"/>
										<xs:element name="value">
											<xs:simpleType>
												<xs:union memberTypes="xs:boolean xs:string xs:integer xs:double xs:decimal xs:date" />												
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Vishvin95/Temporal-Event-Data-Platform/SensorData.xml
<?xml version="1.0" encoding="UTF-8"?>
<sensorData
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="src/main/resources/SensorData.xsd">
	
	<domain name="boilerReadings">
		<reading>
			<key>boilderCode</key>
			<value>B1</value>
		</reading>
		<reading>
			<key>temperature</key>
			<value>23</value>
		</reading>
		<reading>
			<key>pressure</key>
			<value>45</value>
		</reading>
	</domain>
</sensorData>
